export const providersArray = [
	{
		name: "streets",
		provider: "mapbox",
		source: 'composite',
		layer: 'road',
		columnName: "type",
		geometryType: "LineString",
	},
	{
		name: "buildings",
		provider: "mapbox", 
		source: 'composite',
		layer: 'building', 
		columnName: "type", 
		geometryType: "Polygon", 
	},
	{
		name: "structure",
		provider: "mapbox", 
		source: 'composite',
		layer: 'structure', 
		columnName: "type", 
		geometryType: "Polygon", 
	},
	{
		name: "landuse",
		provider: "mapbox", 
		source: 'composite',
		layer: 'landuse', 
		columnName: "type", 
		geometryType: "Polygon", 
	},
	{
		name: "water",
		provider: "mapbox", 
		source: 'composite',
		layer: 'water', 
		columnName: "type", 
		geometryType: "Polygon", 
	},
	{
		name: "waterway",
		provider: "mapbox", 
		source: 'composite',
		layer: 'waterway', 
		columnName: "type", 
		geometryType: "LineString", 
	},
];